extends RefCounted

## 设置系统的全部玩家可见文本。
## 当前为简体中文基线；接入 TranslationServer 后可将这些访问器改为 tr(key)。

const PAUSE_TITLE := "暂停"
const PAUSE_RESUME := "继续游戏"
const PAUSE_SETTINGS := "设置"
const PAUSE_QUIT := "退出游戏"
const PAUSE_RESUME_HINT := "ESC 恢复游戏"

const SETTINGS_TITLE := "设置"
const SETTINGS_SUBTITLE := "修改会即时预览；应用后才能保存到本地。ESC 返回暂停菜单。"
const SETTINGS_CANCEL := "取消"
const SETTINGS_APPLY := "应用"
const SETTINGS_RESTORE_PAGE := "恢复本页默认"
const SETTINGS_UNAVAILABLE_TOOLTIP := "此分类将在对应系统接入后开放"
const SETTINGS_PLACEHOLDER_SUBTITLE := "该分类的服务接口已预留，等待底层系统接入。"
const SETTINGS_COMING_SOON := "即将开放"
const SETTINGS_NO_FAKE_OPTIONS := "这里不会显示无法实际应用的假选项。"
const SETTINGS_SAVE_ERROR := "无法保存设置（错误码 %d）"
const SETTINGS_UNKNOWN_KEY := "Unknown player setting: %s"

const CATEGORY_CONTROLS := "控制"
const CATEGORY_VIDEO := "画面"
const CATEGORY_AUDIO := "音频"
const CATEGORY_INTERFACE := "界面"
const CATEGORY_ACCESSIBILITY := "辅助功能"

const VIDEO_SUBTITLE := "调整窗口显示方式。"
const SECTION_DISPLAY := "显示"
const SECTION_VISUAL_EFFECTS := "视觉特效"
const SECTION_COMFORT := "舒适性"
const SECTION_WEAPON_EFFECTS := "武器特效"
const SECTION_BLOOD_EFFECTS := "血腥效果"
const VIDEO_WINDOW_MODE := "窗口模式"
const VIDEO_WINDOW_MODE_HINT := "选择窗口化或全屏显示。"
const WINDOW_MODE_WINDOWED := "窗口化"
const WINDOW_MODE_FULLSCREEN := "全屏"
const VIDEO_HIT_CAMERA_IMPACT := "受击镜头冲击"
const VIDEO_HIT_CAMERA_IMPACT_HINT := "调整受伤瞬间镜头歪斜和冲击感；设为 0 可关闭。"
const VIDEO_DAMAGE_BLUR := "伤痛与疲劳模糊"
const VIDEO_DAMAGE_BLUR_HINT := "调整受伤、疼痛和低体力造成的屏幕模糊。"
const VIDEO_COMA_EFFECT := "濒死视觉效果"
const VIDEO_COMA_EFFECT_HINT := "控制濒死时的扭曲、重影和暗化效果。"
const VIDEO_DEATH_EFFECT := "死亡视觉效果"
const VIDEO_DEATH_EFFECT_HINT := "控制死亡时的模糊和画面渐黑。"
const VIDEO_DEATH_CAMERA_SHAKE := "死亡镜头晃动"
const VIDEO_DEATH_CAMERA_SHAKE_HINT := "调整布娃娃阶段的轻微镜头晃动。"
const VIDEO_MUZZLE_FLASH := "枪口焰"
const VIDEO_MUZZLE_FLASH_HINT := "显示开火时由枪械配件和枪管长度决定的枪口焰。"
const VIDEO_MUZZLE_LIGHT := "枪口动态光照"
const VIDEO_MUZZLE_LIGHT_HINT := "显示开火瞬间照亮附近环境的动态光源。"
const VIDEO_HEAT_HAZE := "枪口热浪"
const VIDEO_HEAT_HAZE_HINT := "显示开火产生的微妙屏幕空间热浪扭曲。"
const VIDEO_BLOOD_EFFECTS := "血液效果"
const VIDEO_BLOOD_EFFECTS_HINT := "血腥内容：控制死亡后的血泊、滴血等表现。"

const CONTROLS_SUBTITLE := "键位可重绑定；控制台使用 ` / ~ 呼出。ESC 无法绑定其他按键。"
const SECTION_MOUSE_AND_OPTICS := "鼠标与瞄具"
const SECTION_KEYBINDS := "键位绑定"
const CONTROL_SENSITIVITY := "统一灵敏度"
const CONTROL_SENSITIVITY_HINT := "同时调整水平与垂直视角灵敏度。"
const CONTROL_INVERT_Y := "反转 Y 轴"
const CONTROL_INVERT_Y_HINT := "反转鼠标上下移动方向。"
const TOGGLE_ENABLED := "开启"
const BIND_TOOLTIP := "点击后按下新按键；右键点击可清空此槽。"
const BIND_LISTENING := "按下按键…"
const BIND_UNBOUND := "未绑定"
const BIND_EMPTY := "-"

const CONFLICT_TEMPLATE := "“%s” 已被 %s 占用。可替换对方绑定，或明确保留冲突。"
const CONFLICT_REPLACE := "替换占用"
const CONFLICT_KEEP := "保留冲突"
const CONFLICT_WARNING := "存在键位冲突。请在冲突提示中替换占用，或保留明确允许的冲突。"

const CATEGORY_MOVEMENT := "移动"
const CATEGORY_STANCE := "姿态微调"
const CATEGORY_COMBAT := "战斗"
const CATEGORY_DEBUG := "调试"

const ACTION_MOVE_FORWARD := "前进"
const ACTION_MOVE_BACKWARD := "后退"
const ACTION_MOVE_LEFT := "左移"
const ACTION_MOVE_RIGHT := "右移"
const ACTION_JUMP := "跳跃"
const ACTION_SPRINT := "奔跑"
const ACTION_CROUCH := "蹲姿"
const ACTION_STANCE_RAISE := "姿态升高"
const ACTION_STANCE_LOWER := "姿态降低"
const ACTION_FIRE := "开火"
const ACTION_RELOAD := "换弹"
const ACTION_CYCLE_FIRE_MODE := "切换射击模式"
const ACTION_CLEAR_MALFUNCTION := "排障"
const ACTION_TOGGLE_FREE_CAM := "DEBUG：进入自由视角"
const ACTION_WEAPON_MOD_MENU := "DEBUG：打开武器改装界面"
const ACTION_DEBUG_REVIVE := "DEBUG：原地复活并补满弹药"
const ACTION_CONSOLE := "打开运行时控制台"
const ACTION_CONSOLE_HINT := "使用 ` 或 ~ 呼出；打开时世界继续运行但玩家控制会锁定。"
const CONSOLE_TITLE := "运行时控制台"
const CONSOLE_SUBTITLE := "本地调试命令"
const CONSOLE_INPUT_PLACEHOLDER := "> 输入命令"
const CONSOLE_INPUT_HINT := "输入命令后按 Enter 执行"
const CONSOLE_FOOTER_HINT := "Enter 执行    Tab 补全    ↑↓ 历史/选择    Esc 关闭"
const DEBUG_CATEGORY_HINT := "调试命令仅在 Debug 构建中开放。"

const KEY_MOUSE_LEFT := "鼠标左键"
const KEY_MOUSE_RIGHT := "鼠标右键"
const KEY_MOUSE_MIDDLE := "鼠标中键"
const KEY_WHEEL_UP := "滚轮上"
const KEY_WHEEL_DOWN := "滚轮下"
const KEY_MOUSE_BUTTON := "鼠标键 %d"
