extends RefCounted

## 设置系统的全部玩家可见文本。
## 当前为简体中文基线；接入 TranslationServer 后可将这些访问器改为 tr(key)。

const PAUSE_TITLE := "暂停"
const PAUSE_RESUME := "继续游戏"
const PAUSE_SETTINGS := "设置"
const PAUSE_QUIT := "退出游戏"
const PAUSE_RESUME_HINT := "ESC 恢复游戏"

const SETTINGS_TITLE := "设置"
const SETTINGS_SUBTITLE := "修改会即时预览；应用后才能保存到本地。ESC 返回暂停菜单。"
const SETTINGS_CANCEL := "取消"
const SETTINGS_APPLY := "应用"
const SETTINGS_RESTORE_PAGE := "恢复本页默认"
const SETTINGS_UNAVAILABLE_TOOLTIP := "此分类将在对应系统接入后开放"
const SETTINGS_PLACEHOLDER_SUBTITLE := "该分类的服务接口已预留，等待底层系统接入。"
const SETTINGS_COMING_SOON := "即将开放"
const SETTINGS_NO_FAKE_OPTIONS := "这里不会显示无法实际应用的假选项。"
const SETTINGS_SAVE_ERROR := "无法保存设置（错误码 %d）"
const SETTINGS_UNKNOWN_KEY := "Unknown player setting: %s"

const CATEGORY_CONTROLS := "控制"
const CATEGORY_VIDEO := "画面"
const CATEGORY_AUDIO := "音频"
const CATEGORY_INTERFACE := "界面"
const CATEGORY_ACCESSIBILITY := "辅助功能"

const CONTROLS_SUBTITLE := " ESC 无法绑定其他按键。"
const SECTION_MOUSE_AND_OPTICS := "鼠标与瞄具"
const SECTION_KEYBINDS := "键位绑定"
const CONTROL_SENSITIVITY := "统一灵敏度"
const CONTROL_SENSITIVITY_HINT := "同时调整水平与垂直视角灵敏度。"
const CONTROL_INVERT_Y := "反转 Y 轴"
const CONTROL_INVERT_Y_HINT := "反转鼠标上下移动方向。"
const TOGGLE_ENABLED := "开启"
const BIND_TOOLTIP := "点击后按下新按键；右键点击可清空此槽。"
const BIND_LISTENING := "按下按键…"
const BIND_UNBOUND := "未绑定"
const BIND_EMPTY := "-"

const CONFLICT_TEMPLATE := "“%s” 已被 %s 占用。可替换对方绑定，或明确保留冲突。"
const CONFLICT_REPLACE := "替换占用"
const CONFLICT_KEEP := "保留冲突"
const CONFLICT_WARNING := "存在键位冲突。请在冲突提示中替换占用，或保留明确允许的冲突。"

const CATEGORY_MOVEMENT := "移动"
const CATEGORY_STANCE := "姿态微调"
const CATEGORY_COMBAT := "战斗"
const CATEGORY_DEBUG := "调试"

const ACTION_MOVE_FORWARD := "前进"
const ACTION_MOVE_BACKWARD := "后退"
const ACTION_MOVE_LEFT := "左移"
const ACTION_MOVE_RIGHT := "右移"
const ACTION_JUMP := "跳跃"
const ACTION_SPRINT := "奔跑"
const ACTION_CROUCH := "蹲姿"
const ACTION_STANCE_RAISE := "姿态升高"
const ACTION_STANCE_LOWER := "姿态降低"
const ACTION_FIRE := "开火"
const ACTION_RELOAD := "换弹"
const ACTION_CYCLE_FIRE_MODE := "切换射击模式"
const ACTION_CLEAR_MALFUNCTION := "排障"
const ACTION_TOGGLE_FREE_CAM := "DEBUG：进入自由视角"
const ACTION_WEAPON_MOD_MENU := "DEBUG：打开武器改装界面"

const KEY_MOUSE_LEFT := "鼠标左键"
const KEY_MOUSE_RIGHT := "鼠标右键"
const KEY_MOUSE_MIDDLE := "鼠标中键"
const KEY_WHEEL_UP := "滚轮上"
const KEY_WHEEL_DOWN := "滚轮下"
const KEY_MOUSE_BUTTON := "鼠标键 %d"
